/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PainRouteImport } from './routes/pain'
import { Route as AttributesRouteImport } from './routes/attributes'
import { Route as AttributeStoriesRouteImport } from './routes/attribute-stories'
import { Route as ArchetypesRouteImport } from './routes/archetypes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchetypesIdRouteImport } from './routes/archetypes.$id'

const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PainRoute = PainRouteImport.update({
  id: '/pain',
  path: '/pain',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributesRoute = AttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributeStoriesRoute = AttributeStoriesRouteImport.update({
  id: '/attribute-stories',
  path: '/attribute-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypesRoute = ArchetypesRouteImport.update({
  id: '/archetypes',
  path: '/archetypes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypesIdRoute = ArchetypesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchetypesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRouteWithChildren
  '/attribute-stories': typeof AttributeStoriesRoute
  '/attributes': typeof AttributesRoute
  '/pain': typeof PainRoute
  '/profiles': typeof ProfilesRoute
  '/archetypes/$id': typeof ArchetypesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRouteWithChildren
  '/attribute-stories': typeof AttributeStoriesRoute
  '/attributes': typeof AttributesRoute
  '/pain': typeof PainRoute
  '/profiles': typeof ProfilesRoute
  '/archetypes/$id': typeof ArchetypesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRouteWithChildren
  '/attribute-stories': typeof AttributeStoriesRoute
  '/attributes': typeof AttributesRoute
  '/pain': typeof PainRoute
  '/profiles': typeof ProfilesRoute
  '/archetypes/$id': typeof ArchetypesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archetypes'
    | '/attribute-stories'
    | '/attributes'
    | '/pain'
    | '/profiles'
    | '/archetypes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archetypes'
    | '/attribute-stories'
    | '/attributes'
    | '/pain'
    | '/profiles'
    | '/archetypes/$id'
  id:
    | '__root__'
    | '/'
    | '/archetypes'
    | '/attribute-stories'
    | '/attributes'
    | '/pain'
    | '/profiles'
    | '/archetypes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchetypesRoute: typeof ArchetypesRouteWithChildren
  AttributeStoriesRoute: typeof AttributeStoriesRoute
  AttributesRoute: typeof AttributesRoute
  PainRoute: typeof PainRoute
  ProfilesRoute: typeof ProfilesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pain': {
      id: '/pain'
      path: '/pain'
      fullPath: '/pain'
      preLoaderRoute: typeof PainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributes': {
      id: '/attributes'
      path: '/attributes'
      fullPath: '/attributes'
      preLoaderRoute: typeof AttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attribute-stories': {
      id: '/attribute-stories'
      path: '/attribute-stories'
      fullPath: '/attribute-stories'
      preLoaderRoute: typeof AttributeStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetypes': {
      id: '/archetypes'
      path: '/archetypes'
      fullPath: '/archetypes'
      preLoaderRoute: typeof ArchetypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetypes/$id': {
      id: '/archetypes/$id'
      path: '/$id'
      fullPath: '/archetypes/$id'
      preLoaderRoute: typeof ArchetypesIdRouteImport
      parentRoute: typeof ArchetypesRoute
    }
  }
}

interface ArchetypesRouteChildren {
  ArchetypesIdRoute: typeof ArchetypesIdRoute
}

const ArchetypesRouteChildren: ArchetypesRouteChildren = {
  ArchetypesIdRoute: ArchetypesIdRoute,
}

const ArchetypesRouteWithChildren = ArchetypesRoute._addFileChildren(
  ArchetypesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchetypesRoute: ArchetypesRouteWithChildren,
  AttributeStoriesRoute: AttributeStoriesRoute,
  AttributesRoute: AttributesRoute,
  PainRoute: PainRoute,
  ProfilesRoute: ProfilesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
